/* This file is generated by glib-genmarshal, do not modify it. This code is licensed under the same license as the containing project. Note that it links to GLib, so must comply with the LGPL linking clauses. */
#ifndef __GTK_DATABOX_MARSHAL_MARSHAL_H__
#define __GTK_DATABOX_MARSHAL_MARSHAL_H__

#include <glib-object.h>

G_BEGIN_DECLS

/* VOID:VOID (gtkdatabox_marshal.list:1) */
#define gtk_databox_marshal_VOID__VOID	g_cclosure_marshal_VOID__VOID

/* VOID:POINTER (gtkdatabox_marshal.list:2) */
#define gtk_databox_marshal_VOID__POINTER	g_cclosure_marshal_VOID__POINTER


G_END_DECLS

#endif /* __GTK_DATABOX_MARSHAL_MARSHAL_H__ */
